name: Kloeten
version: '1.0'
main: com.soupersgg.kloeten.Kloeten
api-version: '1.21'

commands:
  lobby:
    description: Command to handle lobby functionality
    aliases: [l]
  lobby_spawn:
    description: Command to handle lobby spawn
  lobby_minigames:
    description: Command to handle lobby minigames
  report:
    description: Command to report a player
  friend:
    description: Command to manage friends
  party:
    description: Command to manage parties
  clan:
    description: Command to manage clans